steps:
  - name: gcr.io/cloud-builders/git
    args: ["fetch", "--unshallow"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: get-build-number
    script: | 
      echo $(date +'%Y%m%d').$(expr $(git rev-list --count master) - $(git rev-list --count master --since=$(date -d '1 days ago' +'%d-%m-%Y'))) > BUILD_NO
      echo $(cat BUILD_NO)

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: build-dataflow-container
    env:
    - PROJECT=${PROJECT_ID}
    - IMAGE_NAME=gcr.io/${PROJECT_ID}/intro_beam:$(cat BUILD_NO)
    - TEMPLATE_LOCATION=gs://dataflow-image-custom/templates/$(cat BUILD_NO).json
    script: |
      chmod +x ./deploy/build.sh
      sh ./deploy/build.sh
    waitFor: 
      - get-build-number

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: build-dataflow-template
    env:
    - JOB_NAME=intro-beam
    - IMAGE_NAME=gcr.io/${PROJECT_ID}/intro_beam:$(cat BUILD_NO)
    - TEMPLATE_LOCATION=gs://dataflow-image-custom/templates/$(cat BUILD_NO).json
    script: |
      chmod +x ./deploy/run.sh
      sh ./deploy/run.sh
    waitFor:
      - build-dataflow-container
tags: ["my-tag"]

