steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: get-build-number
    args:
    - -c
    - |
      echo "export BUILD_NO=$(date +'%Y%m%d.%H%M%S')" >> $HOME/.bashrc
      source $HOME/.bashrc
    env:
    - 'HOME=/builder/home'
    - 'BASH_ENV=/builder/home/.bashrc'
  
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: build-dataflow-container
    env:
    - PROJECT=${PROJECT_ID}
    - IMAGE_NAME=gcr.io/${PROJECT_ID}/intro_beam:${BUILD_NO}
    - TEMPLATE_LOCATION=gs://dataflow-image-custom/templates/${BUILD_NO}.json
    script: |
      chmod +x ./deploy/build.sh
      sh ./deploy/build.sh
    waitFor: 
      - get-build-number

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: build-dataflow-template
    env:
    - JOB_NAME=intro-beam-${BUILD_NO}
    - IMAGE_NAME=gcr.io/${PROJECT_ID}/intro_beam:${BUILD_NO}
    - TEMPLATE_LOCATION=gs://dataflow-image-custom/templates/${BUILD_NO}.jso
    script: |
      chmod +x ./deploy/run.sh
      sh ./deploy/run.sh
    waitFor:
      - build-dataflow-container
tags: ["my-tag"]

