steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'build-dataflow-container'
    entrypoint: 'gcloud'
    args: [ 'builds', 'submit', '--project=$PROJECT_ID', '--tag', '${_IMAGE_NAME}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'build-dataflow-template'
    entrypoint: 'gcloud'
    args: [ 'dataflow', 'flex-template', 'build', '${_TEMPLATE_GCS_LOCATION}', '--image', '${_IMAGE_NAME}', '--sdk-language', 'PYTHON', '--metadata-file', 'deploy/metadata.json']
substitutions:
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/intro_beam:${SHORT_SHA}'
  _TEMPLATE_GCS_LOCATION: gs://dataflow-image-custom/template
options:
  dynamic_substitutions: True

