steps:
  - name: gcr.io/cloud-builders/docker
    id: get-build-number
    entrypoint: bash
    args:
    - -c
    - echo $(date +'%Y%m%d.%H%M%S') > build.txt

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: build-dataflow-container
    env:
    - PROJECT=${PROJECT_ID}
    script: |
      chmod +x ./deploy/build.sh
      export IMAGE_NAME=gcr.io/${PROJECT}/intro_beam:$(cat build.txt)
      export TEMPLATE_LOCATION=gs://dataflow-image-custom/templates/$(cat build.txt).json
      sh ./deploy/build.sh
    waitFor: 
      - get-build-number
